nodeLinker: pnp

# We want to use 'zero-install' so that we do not need
# to be reliant on having a (good) internet connection
enableGlobalCache: false

supportedArchitectures:
  os:
    - "win32"
    - "darwin"
    - "linux"
  cpu:
    - "x64"
    - "arm64"
  libc:
    - "glibc"
    - "musl"
