[tools]
python = "3.14.3"
pre-commit = "4.5.1"
node = { version = "24.14.0", postinstall = "corepack enable" }
rust = { version = "1.94.0", profile = "minimal", components = "rustfmt" }
uv = "0.10.9"

[tasks.start]
run = "uv run python -m mandelbrot"

[tasks.present]
dir = "src/presentation"
run = "yarn start"

[env]
MISE_NODE_COREPACK = true

[settings]
python.uv_venv_auto = "create|source"
