[tools]
python = "3.13.2"
pre-commit = "4.2.0"
node = { version = " 22.15.1", postinstall = "corepack enable" }
rust = { version = "1.87.0", profile = "minimal", components = "rustfmt" }
uv = "0.7.19"

[tasks.start]
run = "uv run python -m mandelbrot"

[env]
MISE_NODE_COREPACK = true

[settings]
python.uv_venv_auto = "create|source"
