[project]
name = "mandelbrot"
version = "0.1.0"
description = "Live deomonstration of the Mandelbrot set to illustrate performance improvements in Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colorcet>=3.1.0",
    "numpy>=2.2.6",
    "pygame>=2.6.1",
]
